---
title: "Data Analysis"                    
author: "Dr. Muhammad Saufi"              
date: 14 August 2024                      
format:                                   
  html:                                   
    toc: true                             
    toc-title: Contents                   
    toc-location: left                    
    toc-depth: 3                          
    toc-expand: 1                         
    number-sections: true                 
    code-fold: true                       
    code-summary: "Show the Code"         
    theme:                                
      light: united                       
      dark: cyborg                        
    embed-resources: true                 
editor: visual
---

# Setting the Environment                          
## Loading the Packages                            

```{r}                                             
# Load the packages into R session                 
library(tidyverse)                                 
```                                                

# Dataset                                          
## Reading the Dataset                             
                                                   
```{r}                                             
# Import the dataset into workspace                
penguins <- read_csv("Datasets/penguins.csv")      
```                                                

## Exploring the Dataset                           

```{r}                                             
# Get a quick overview of dataset                  
glimpse(penguins)                                  
```

## Visualize the Dataset

```{r}                                             
ggplot(                                   
  data = penguins,                        
  mapping = aes(                          
             x = flipper_length_mm,       
             y = body_mass_g,             
             color = species)             
) +                                       
  geom_point()
```
